home:
    path: /
    controller: App\Controller\DefaultController::index
    
posts.index:
    path: /posts
    controller: App\Controller\PostController::index
    
posts.show:
    path: /posts/{id}
    controller: App\Controller\PostController::show
    requirements:
        id: '\d+'

hello:
    path: /hello/name/{name}/age/{age}
    controller: App\Controller\DefaultController::hello
    requirements:
        age: '\d+'